index:
    path: /
    controller: App\Controller\DefaultController::index

weatherGeneral:
    path: /w/{source}
    controller: App\Controller\DefaultController::weatherGeneral
    requirements:
        source: '\d+'

weatherRainMinutely:
    path: /r/{source}
    controller: App\Controller\DefaultController::weatherRainMinutely
    requirements:
        source: '\d+'
