# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Fetcher\Mb\MbFetcher:
        factory: [ 'App\Fetcher\Mb\MbFetcher', 'create' ]
        arguments:
            $url1: '%env(MB_URL_1)%'

    App\Fetcher\Mb\MbCachedFetcher:
        arguments:
            $fetcher: '@App\Fetcher\Mb\MbFetcher'
            $cachePath: '%kernel.project_dir%/var/cache/mb'

    App\Parser\Mb\MbParser:
        arguments:
            $fetcher: '@App\Fetcher\Mb\MbCachedFetcher'

    App\Fetcher\Oc\OcFetcher:
        factory: [ 'App\Fetcher\Oc\OcFetcher', 'create' ]
        arguments:
            $url1: '%env(OC_URL_1)%'

    App\Fetcher\Oc\OcCachedFetcher:
        arguments:
            $fetcher: '@App\Fetcher\Oc\OcFetcher'
            $cachePath: '%kernel.project_dir%/var/cache/oc'

    App\Parser\Oc\OcParserMinutely:
        arguments:
            $fetcher: '@App\Fetcher\Oc\OcCachedFetcher'

    App\Parser\Oc\OcParserDaily:
        arguments:
            $fetcher: '@App\Fetcher\Oc\OcCachedFetcher'

    App\Fetcher\Fc\FcFetcher:
        factory: [ 'App\Fetcher\Fc\FcFetcher', 'create' ]
        arguments:
            $url1: '%env(FC_URL_1)%'

    App\Fetcher\Fc\FcCachedFetcher:
        arguments:
            $fetcher: '@App\Fetcher\Fc\FcFetcher'
            $cachePath: '%kernel.project_dir%/var/cache/fc'
    
    App\Parser\Fc\FcParserForecast:
        arguments:
            $fetcher: '@App\Fetcher\Fc\FcCachedFetcher'

